#+OPTIONS: toc:nil H:10 tex:t
#+TITLE: 
#+STARTUP: odd hidestars indent
#+INCLUDE: personal-info.org
#+LaTeX_HEADER: \usepackage{mycv}
#+LaTeX_HEADER: \hypersetup{hidelinks}
#+LaTeX_CLASS_OPTIONS: [11pt,letterpaper]

{{{HEADER}}}

* Profile
Professional embedded system engineer with five years of experience in microcontroller and Linux app development. Involved in machine architecture planning and lead a small programmer team. 
  
* Skills
- Languages :: Chinese (native), English (proficient), Japanese (proficient)
- Programming Languages :: C, Python, javascript, C++
- C Compiler/IDE :: GCC toolchain, ARM toolchain, Keil, IAR
- Hardware Development :: Verilog, ISE, QartusII, Libero, OrCad

* Experience
*** Ackuretta Technologies (3D printer)
***** Nov. 2016 - Present
******* Senior Firmware Engineer
- Added completed firmware shutdown protection including shutdown motor protection and printing model resuming.
- Built an performance/security balanced encrypted system to protect product from pirate copying.
- Shorten the time to market of 3D printer 4 weeks by created a machine live monitor program for experiment analysis.

*** International Game System co., ltd. (Arcade gaming machine)
***** April 2016 - Oct. 2016
******* Senior Hardware Engineer 
- Established more than 10 firmware of arcade machine including controlling motors and driving I2C/SPI/CAN bus/UART interface device.
- Implemented FPGA product Intellectual property protector.
- Saved more than 80% flash memory of microcontroller by implement compressed algorithm into the chip.

* Education
*** National Taiwan University Science and Technology
***** Sept. 2011 - June 2013
******* M.E.E., Electrical and Engineering
- Thesis: Efficient Test and Repair Architectures for Logic Memory Stacked 3D ICs
- Advisor: Prof. Shyue-Kung Lu
- GPA: 3.88/4


  
