#+OPTIONS: toc:nil H:10 tex:t
#+TITLE: 
#+STARTUP: odd hidestars indent
#+INCLUDE: personal-info.org
#+LaTeX_HEADER: \usepackage{mycv}
#+LaTeX_HEADER: \usepackage{tikz}
#+LaTeX_HEADER: \usepackage{indentfirst}
#+LaTeX_HEADER: \setlength{\parindent}{15pt}
#+LaTeX_HEADER: \hypersetup{hidelinks}

#+LaTeX_CLASS_OPTIONS: [10pt,letterpaper]

{{{HEADER}}}

* Profile
Professional embedded system engineer with five years of experience in microcontroller and Linux app development. Involved in machine architecture planning and lead a small programmer team. 
  
* Skills
- Languages :: Chinese (native), English (proficient), Japanese (proficient)
- Programming Languages :: C, Python, javascript, C++
- C Compiler/IDE :: GCC toolchain, ARM toolchain, Keil, IAR
- Hardware Development :: Verilog, ISE, QartusII, Libero, OrCad, gEDA

* Experience
*** Ackuretta Technologies (3D printer)
***** Nov. 2016 - Present
******* Senior Firmware Engineer
- Designed a microcontroller firmware for DLP 3D printer with a portable size protocol that can communicate with Linux system.
- Wrote a DLP 3D printer control system in embedded Linux which is much flexible for the user to adjust several variables for printing.
- Managed a 2 people firmware team and keep tracking the performance of our team members.
- Built a performance/security balanced encrypted system to protect the product from pirate copying.
- Shorten the time to market of 3D printer 4 weeks by creating a machine live monitor program with python for experiment analysis.

*** International Game System co., Ltd. (Arcade gaming machine)
***** April 2016 - Oct. 2016
******* Senior Hardware Engineer 
- Established more than 10 firmware of arcade machines including controlling motors and driving I2C/SPI/CAN bus/UART interface device.
- Implemented FPGA product Intellectual property protector.
- Saved more than 80% flash memory of microcontroller by implement compressed algorithm into the chip.

* Education
*** National Taiwan University Science and Technology
***** Sept. 2011 - June 2013
******* M.E.E., Electrical, and Engineering
- Thesis: Efficient Test and Repair Architectures for Logic Memory Stacked 3D ICs
- Advisor: Prof. Shyue-Kung Lu
- GPA: 3.88/4

  
